# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/python/black/
    rev: 19.3b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-broken-line
          - flake8-builtins
          - flake8-functions
          - pydocstyle
