name: Create and test application

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
                  pip install -r requirements-test.txt

            - name: Lint with flake8
              run: |
                  flake8

            - name: Test with pytest
              run: |
                  pytest

            - name: Check style with Black
              run: |
                  black --check --diff chatovod tests

            - name: Generate coverage report
              run: |
                  pytest --cov=./ --cov-report=xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  yml: ./codecov.yml
                  fail_ci_if_error: true
